/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projetopoo.interfacegrafica;

import com.mycompany.projetopoo.interfacegrafica.Codigo.Restaurante;

/**
 * Classe que representa os cards de restaurante
 * @author jaoti
 */
public class JPanelRestaurante extends javax.swing.JPanel {

    /**
     * Creates new form JPanelRestaurante
     */
    
    //Variavel para facilitar a vida
    private final Restaurante restaurante;
    
    /**
     * Retorna o restaurante do card
     * @return Restaurante
     */
    public Restaurante getRestaurante(){
        return restaurante;
    }
    
    /**
     * Carrega os dados no card
     */
    private void carregarDados(){
        //Coloca a imagem na label
        this.lblImg.setIcon(JFrameLogin.getImageIconFromPath(restaurante.getResolvedProfilePath(),80));
        
        //Carregar o texto
        lblNome.setText(restaurante.getNomeReal());
        lblNPedidos.setText("Nº Pedidos: " + String.valueOf(restaurante.getPedidos().size()));
    }

    /**
     * Construtor do panel do card de cada restaurante
     * @param restaurante
     */
    public JPanelRestaurante(Restaurante restaurante) {
        initComponents();
        this.restaurante = restaurante;
        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblNPedidos = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 2147483647));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBackground(new java.awt.Color(184, 170, 160));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblImg.setAlignmentX(0.5F);
        lblImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImg.setMaximumSize(new java.awt.Dimension(80, 80));
        lblImg.setMinimumSize(new java.awt.Dimension(80, 80));
        lblImg.setPreferredSize(new java.awt.Dimension(80, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblImg, gridBagConstraints);

        lblNome.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblNome.setText("Nome do restaurante");
        lblNome.setAlignmentX(0.5F);
        lblNome.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(lblNome, gridBagConstraints);

        lblNPedidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNPedidos.setText("Endereco do restaurante");
        lblNPedidos.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(lblNPedidos, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNPedidos;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
