/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projetopoo.interfacegrafica;

import com.mycompany.projetopoo.interfacegrafica.Codigo.Item;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JSpinner;

/**
 * Panel que serve como card para cada item
 * @author jaoti
 */
public class JPanelItem extends javax.swing.JPanel {

    /**
     * Creates new form jPanelItem
     */
    
    //Enum para verificar onde esse panel é usado
    public enum Tela{
        CARDAPIO,   //Quando o cliente vai adicionar no carrinho
        CARRINHO,   //No carrinnho do cliente
        LISTA,      //Na listagem de items para o restaurante
        PEDIDO      //Na lista de items do pedido
    }
    
    private Tela tela;
    //Variaveis para ajudar no sistema
    private final Item item;
    private int quantidade;
    
    /**
     * Retorna o JSpinner da quantidade
     * @return JSpinner da quantidade
     **/
    public JSpinner getNmbQuantidade(){
        return nmbQuantidade;
    }
    
    /**
     * Coloca a quantidade de item no card
     * @param quantidade
     **/
    public void setQuantidade(int quantidade){
        this.quantidade = quantidade;
        nmbQuantidade.setValue(quantidade);
    }
    
    /**
     * Retorna a quantidade selecionada do item
     * @return Quantidade
     **/
    public int getQuantidade(){
        return quantidade;
    }
    
    /**
     * Retorna o Item do card
     * @return Item
     **/
    public Item getItem(){
        return item;
    }
    
    /**
     * Retorna o botão de adicionar o item ao carrinho
     * @return Botão de adicionar ao carrinho
     **/
    public JButton getAddButton(){
        return this.btnAddCarrinho;
    }
    
    /**
     * Coloca os dados no card
     **/
    private void carregarDados(){

        //Carregar Imagem
        this.lblImg.setIcon(JFrameLogin.getImageIconFromPath(item.getResolvedImgPath(),50)); 
        //Carregar o texto
        lblNome.setText(item.getNome());
        lblTipo.setText(item.getTipo());
        lblPreco.setText("R$" + item.getPreco());
        //Carregar quantidade
        nmbQuantidade.setValue(quantidade);
    }
    
    /**
     * Muda o design de algums componentes baseado em que tela está aparecendo
     * @param tela
     */
    private void decidirDesign(Tela tela){
        switch(tela){
            case CARDAPIO -> this.setCursor(Cursor.getDefaultCursor());
            case CARRINHO -> {
                btnAddCarrinho.setVisible(false);
                this.setCursor(Cursor.getDefaultCursor());
            }
            case LISTA -> {
                panelOpcoes.setVisible(false);
                this.setOpaque(false);
                //HAND CURSOR está setado
            }
            case PEDIDO -> {
                btnAddCarrinho.setVisible(false);
                nmbQuantidade.setEnabled(false);
                this.setCursor(Cursor.getDefaultCursor());
            }
        }
        
    }
    
    /**
    * Construtor do panel (Card) de item
    * @param item
    * @param tela
    */
    public JPanelItem(Item item,Tela tela) {
        initComponents();
        this.item = item;
        carregarDados();
        this.nmbQuantidade.setValue(1); //Começa com 1 quantidade de item selecionado
        decidirDesign(tela);
        this.tela = tela;
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        panelOpcoes = new javax.swing.JPanel();
        nmbQuantidade = new javax.swing.JSpinner();
        btnAddCarrinho = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        setForeground(new java.awt.Color(51, 51, 51));
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(184, 170, 160));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 5));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.1F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblImg.setBackground(new java.awt.Color(255, 102, 255));
        lblImg.setToolTipText("");
        lblImg.setAlignmentX(0.5F);
        lblImg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImgMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(lblImg, gridBagConstraints);

        lblNome.setBackground(new java.awt.Color(102, 255, 102));
        lblNome.setText("Nome Produto");
        lblNome.setAlignmentX(0.5F);
        lblNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblNome, gridBagConstraints);

        lblTipo.setText("Tipo do Produto");
        lblTipo.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblTipo, gridBagConstraints);

        lblPreco.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblPreco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreco.setText("R$99,99");
        lblPreco.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        jPanel1.add(lblPreco, gridBagConstraints);

        panelOpcoes.setOpaque(false);
        panelOpcoes.setLayout(new java.awt.GridBagLayout());

        nmbQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        nmbQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nmbQuantidadeStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        panelOpcoes.add(nmbQuantidade, gridBagConstraints);

        btnAddCarrinho.setText("+");
        btnAddCarrinho.setAlignmentX(0.5F);
        btnAddCarrinho.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        panelOpcoes.add(btnAddCarrinho, gridBagConstraints);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTotal.setText("Total: R$999,99");
        lblTotal.setAlignmentX(0.5F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        panelOpcoes.add(lblTotal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(panelOpcoes, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Atualiza o total quando a quantidade de um item muda e atualiza a qantidade total
    */
    private void nmbQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nmbQuantidadeStateChanged
        lblTotal.setText("Total: " + "R$" + ((int)nmbQuantidade.getValue())*item.getPreco());
        quantidade = (int)nmbQuantidade.getValue();
        if(tela == Tela.CARRINHO){
            if((int)nmbQuantidade.getValue() == 0) this.jPanel1.setBackground(new Color(242,126,110));
            else this.jPanel1.setBackground(new Color(184,170,160));
        }
    }//GEN-LAST:event_nmbQuantidadeStateChanged

   /*
    * Método para passar o evento de clique na label da imagem para frente (Não passa sozinho por algum motivo)
    */
    private void lblImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImgMouseClicked
        for( MouseListener listener : this.getMouseListeners()){
            listener.mouseClicked(evt);
        }
    }//GEN-LAST:event_lblImgMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCarrinho;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner nmbQuantidade;
    private javax.swing.JPanel panelOpcoes;
    // End of variables declaration//GEN-END:variables
}
